<?xml version="1.0" encoding="utf-8"?><Database Name="DataEntry" Class="HotelDataEntryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=61.90.202.67;Initial Catalog=DataEntry;Persist Security Info=True;User ID=sa" SettingsObjectName="HotelDataEntryLib.Properties.Settings" SettingsPropertyName="DataEntryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Currency" Member="Currencies">
    <Type Name="Currency">
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrencyCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConversionRate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsBase" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Currency_Property" Member="Properties" ThisKey="CurrencyId" OtherKey="CurrencyId" Type="Property" />
    </Type>
  </Table>
  <Table Name="dbo.Property" Member="Properties">
    <Type Name="Property">
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BrandId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_Property" Member="User" ThisKey="PropertyId" OtherKey="PropertyId" Type="User" IsForeignKey="true" />
      <Association Name="Currency_Property" Member="Currency" ThisKey="CurrencyId" OtherKey="CurrencyId" Type="Currency" IsForeignKey="true" />
      <Association Name="Brand_Property" Member="Brand" ThisKey="BrandId" OtherKey="BrandId" Type="Brand" IsForeignKey="true" />
      <Association Name="HotelEntry_Property" Member="HotelEntry" ThisKey="PropertyId" OtherKey="PropertyId" Type="HotelEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AlterPropertyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Property" Member="Properties" ThisKey="PropertyId" OtherKey="PropertyId" Type="Property" />
      <Association Name="Permission_User" Member="Permission" ThisKey="PermissionId" OtherKey="PermissionId" Type="Permission" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Brand" Member="Brands">
    <Type Name="Brand">
      <Column Name="BrandId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BrandCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BrandName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Brand_Property" Member="Properties" ThisKey="BrandId" OtherKey="BrandId" Type="Property" />
    </Type>
  </Table>
  <Table Name="dbo.ErrorLog" Member="ErrorLogs">
    <Type Name="ErrorLog">
      <Column Name="ErrorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ErrorMsg" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ErrorDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Permission" Member="Permissions">
    <Type Name="Permission">
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACInputFrom" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ACReport" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ACCompany" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ACUser" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ACCurrency" Type="System.Data.Linq.Binary" DbType="Binary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Permission_User" Member="Users" ThisKey="PermissionId" OtherKey="PermissionId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.DataEntryType" Member="DataEntryTypes">
    <Type Name="DataEntryType">
      <Column Name="DataEntryTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DataEntryTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DataEntrySubType_DataEntryType" Member="DataEntrySubType" ThisKey="DataEntryTypeId" OtherKey="DataEntryTypeId" Type="DataEntrySubType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DataEntry" Member="DataEntries">
    <Type Name="DataEntry">
      <Column Name="DataEntryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ActualData" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Budget" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="YTDActual" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="YTDBudget" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PositionDate" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="HotelEntryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HotelEntry_DataEntry" Member="HotelEntry" ThisKey="HotelEntryId" OtherKey="HotelEntryId" Type="HotelEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HotelEntry" Member="HotelEntries">
    <Type Name="HotelEntry">
      <Column Name="HotelEntryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataEntrySubTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MonthYear" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="HotelEntry_DataEntrySubType" Member="DataEntrySubTypes" ThisKey="DataEntrySubTypeId" OtherKey="DataEntrySubTypeID" Type="DataEntrySubType" />
      <Association Name="HotelEntry_DataEntry" Member="DataEntries" ThisKey="HotelEntryId" OtherKey="HotelEntryId" Type="DataEntry" />
      <Association Name="HotelEntry_Property" Member="Properties" ThisKey="PropertyId" OtherKey="PropertyId" Type="Property" />
    </Type>
  </Table>
  <Table Name="dbo.DataEntrySubType" Member="DataEntrySubTypes">
    <Type Name="DataEntrySubType">
      <Column Name="DataEntrySubTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataEntrySubTypeName" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataEntryTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DataEntrySubType_DataEntryType" Member="DataEntryTypes" ThisKey="DataEntryTypeId" OtherKey="DataEntryTypeId" Type="DataEntryType" />
      <Association Name="HotelEntry_DataEntrySubType" Member="HotelEntry" ThisKey="DataEntrySubTypeID" OtherKey="DataEntrySubTypeId" Type="HotelEntry" IsForeignKey="true" />
    </Type>
  </Table>
</Database>