<?xml version="1.0" encoding="utf-8"?><Database Name="HotelDataEntry" Class="HotelDataEntryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SHQDSPS1\ONCOMOSQL;Initial Catalog=HotelDataEntry;Persist Security Info=True;User ID=dataentry" SettingsObjectName="HotelDataEntryLib.Properties.Settings" SettingsPropertyName="DataEntryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="ErrorDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClientIP" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Currency" Member="Currencies">
    <Type Name="Currency">
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrencyCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConversionRate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsBase" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Currency_Property" Member="Properties" ThisKey="CurrencyId" OtherKey="CurrencyId" Type="Property" />
    </Type>
  </Table>
  <Table Name="dbo.Property" Member="Properties">
    <Type Name="Property">
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PropertyName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Currency_Property" Member="Currency" ThisKey="CurrencyId" OtherKey="CurrencyId" Type="Currency" IsForeignKey="true" />
      <Association Name="HotelRevenue_Property" Member="HotelRevenue" ThisKey="PropertyId" OtherKey="PropertyId" Type="HotelRevenue" IsForeignKey="true" />
      <Association Name="HotelBudget_Property" Member="HotelBudget" ThisKey="PropertyId" OtherKey="PropertyId" Type="HotelBudget" IsForeignKey="true" />
      <Association Name="User_Property" Member="User" ThisKey="PropertyId" OtherKey="PropertyId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HotelRevenue" Member="HotelRevenues">
    <Type Name="HotelRevenue">
      <Column Name="HotelRevenueId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Month" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HotelRevenue_Property" Member="Properties" ThisKey="PropertyId" OtherKey="PropertyId" Type="Property" />
      <Association Name="HotelRevenue_RevenueEntry" Member="RevenueEntries" ThisKey="HotelRevenueId" OtherKey="HotelRevenueId" Type="RevenueEntry" />
    </Type>
  </Table>
  <Table Name="dbo.HotelBudget" Member="HotelBudgets">
    <Type Name="HotelBudget">
      <Column Name="HotelBudgetId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="HotelBudget_Property" Member="Properties" ThisKey="PropertyId" OtherKey="PropertyId" Type="Property" />
      <Association Name="HotelBudget_BudgetEntry" Member="BudgetEntries" ThisKey="HotelBudgetId" OtherKey="HotelBudgetId" Type="BudgetEntry" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="AccessProperties" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Property" Member="Properties" ThisKey="PropertyId" OtherKey="PropertyId" Type="Property" />
      <Association Name="Permission_User" Member="Permission" ThisKey="PermissionId" OtherKey="PermissionId" Type="Permission" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permission" Member="Permissions">
    <Type Name="Permission">
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PermissionName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PermissionCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Permission_User" Member="Users" ThisKey="PermissionId" OtherKey="PermissionId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.BudgetEntry" Member="BudgetEntries">
    <Type Name="BudgetEntry">
      <Column Name="BudgetId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HotelBudgetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PositionMonth" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="OccupancyRoom" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RoomBudget" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="FBBudget" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SpaBudget" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Others" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UpdateUser" Type="System.String" DbType="NVarChar(600)" CanBeNull="true" />
      <Association Name="HotelBudget_BudgetEntry" Member="HotelBudget" ThisKey="HotelBudgetId" OtherKey="HotelBudgetId" Type="HotelBudget" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RevenueEntry" Member="RevenueEntries">
    <Type Name="RevenueEntry">
      <Column Name="RevenueId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PositionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HotelRevenueId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OccupancyRoom" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="RoomRevenue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="FBRevenue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SpaRevenue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Others" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateUser" Type="System.String" DbType="NVarChar(600)" CanBeNull="true" />
      <Association Name="HotelRevenue_RevenueEntry" Member="HotelRevenue" ThisKey="HotelRevenueId" OtherKey="HotelRevenueId" Type="HotelRevenue" IsForeignKey="true" />
    </Type>
  </Table>
</Database>