<?xml version="1.0" encoding="utf-8"?><Database Name="DataEntry" Class="HotelDataEntryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=61.90.202.67;Initial Catalog=DataEntry;Persist Security Info=True;User ID=sa" SettingsObjectName="HotelDataEntryLib.Properties.Settings" SettingsPropertyName="DataEntryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="ErrorDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Detail" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClientIP" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="AccessProperties" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Property" Member="Properties" ThisKey="PropertyId" OtherKey="PropertyId" Type="Property" />
      <Association Name="Permission_User" Member="Permission" ThisKey="PermissionId" OtherKey="PermissionId" Type="Permission" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Currency" Member="Currencies">
    <Type Name="Currency">
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrencyCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConversionRate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsBase" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Currency_Property" Member="Properties" ThisKey="CurrencyId" OtherKey="CurrencyId" Type="Property" />
    </Type>
  </Table>
  <Table Name="dbo.HotelDataEntry" Member="HotelDataEntries">
    <Type Name="HotelDataEntry">
      <Column Name="HotelEntryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MonthYear" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="HotelDataEntry_RevenueEntry" Member="RevenueEntries" ThisKey="HotelEntryId" OtherKey="HotelEntryId" Type="RevenueEntry" />
      <Association Name="HotelDataEntry_BudgetEntry" Member="BudgetEntries" ThisKey="HotelEntryId" OtherKey="HotelEntryId" Type="BudgetEntry" />
      <Association Name="HotelDataEntry_Property" Member="Properties" ThisKey="PropertyId" OtherKey="PropertyId" Type="Property" />
    </Type>
  </Table>
  <Table Name="dbo.RevenueEntry" Member="RevenueEntries">
    <Type Name="RevenueEntry">
      <Column Name="RevenueId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PositionDate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HotelEntryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OccupiedRoom" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalRevenues" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Food" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Beverage" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Service" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Spa" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Others" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="HotelDataEntry_RevenueEntry" Member="HotelDataEntry" ThisKey="HotelEntryId" OtherKey="HotelEntryId" Type="HotelDataEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permission" Member="Permissions">
    <Type Name="Permission">
      <Column Name="PermissionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PermissionName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PermissionCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Permission_User" Member="Users" ThisKey="PermissionId" OtherKey="PermissionId" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.BudgetEntry" Member="BudgetEntries">
    <Type Name="BudgetEntry">
      <Column Name="BudgetId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HotelEntryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PositionDate" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="OccupiedRoom" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalRevenues" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Food" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Beverage" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Service" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Spa" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Others" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Total" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HotelDataEntry_BudgetEntry" Member="HotelDataEntry" ThisKey="HotelEntryId" OtherKey="HotelEntryId" Type="HotelDataEntry" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Property" Member="Properties">
    <Type Name="Property">
      <Column Name="PropertyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PropertyName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CurrencyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdateDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Property" Member="User" ThisKey="PropertyId" OtherKey="PropertyId" Type="User" IsForeignKey="true" />
      <Association Name="Currency_Property" Member="Currency" ThisKey="CurrencyId" OtherKey="CurrencyId" Type="Currency" IsForeignKey="true" />
      <Association Name="HotelDataEntry_Property" Member="HotelDataEntry" ThisKey="PropertyId" OtherKey="PropertyId" Type="HotelDataEntry" IsForeignKey="true" />
    </Type>
  </Table>
</Database>